# Generated by Django 6.0.4 on 2026-07-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
